In [5]:
import numpy as np 
my_list=[1,2,3]
arr=np.array(my_list)
print(arr)
arr

[1 2 3]


array([1, 2, 3])

In [6]:
import numpy as np 
my_list=[[1,2,3],[3,4,5],[5,6,7]]
arr=np.array(my_list)
print(arr)
arr
arr1=np.arange(2,12,3)
print(arr1)
arr1

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[ 2  5  8 11]


array([ 2,  5,  8, 11])

In [7]:
import numpy as np 
arr=np.zeros((3,3))
arr1=np.ones(5)
arr2=np.zeros(4)
arr3=np.ones((3,5))
print(arr)
print(arr1)
print(arr2)
print(arr3)
arr4=np.linspace(1,2,30)
print(arr4)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1.         1.03448276 1.06896552 1.10344828 1.13793103 1.17241379
 1.20689655 1.24137931 1.27586207 1.31034483 1.34482759 1.37931034
 1.4137931  1.44827586 1.48275862 1.51724138 1.55172414 1.5862069
 1.62068966 1.65517241 1.68965517 1.72413793 1.75862069 1.79310345
 1.82758621 1.86206897 1.89655172 1.93103448 1.96551724 2.        ]


In [8]:
import  numpy as np 
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
import numpy as np 
arr1=np.random.rand(5)
print(arr1)
arr2=np.random.randn(5)
print(arr2)
arr3=np.random.randint(1,100,25)
print(arr3)
arr=np.arange(25)
print(arr)
ranarr=np.random.randint(0,50,10)
print(ranarr)
larr=arr.reshape(5,5)
print(larr)
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())
print(ranarr.argmin())

[0.3818578  0.71473243 0.45735063 0.86536409 0.3267611 ]
[-1.29042143 -1.02622749  0.08605498  1.12345585  0.32404713]
[19 51 51 36 80 97 12 50 13 18 86 76 32  7 19 69 55 88 71 20 37 25 41  3
 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[45 22 13 16 42  9 37  1 40 22]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
45
0
1
7


In [10]:
import numpy as np 
arr=np.arange(0,11)
arr[3]
print(arr[3])
print(arr[1:5])
print(arr[2:])

arr[0:5]=99
print(arr)
arr1=np.arange(0,5)
print(arr1[:])
arr_copy=arr1.copy()
arr_copy[:]=False
print(arr_copy)

3
[1 2 3 4]
[ 2  3  4  5  6  7  8  9 10]
[99 99 99 99 99  5  6  7  8  9 10]
[0 1 2 3 4]
[0 0 0 0 0]


In [11]:
import numpy as np 
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d[1,2])
print(arr_2d[:2,1:])
arr1=np.arange(1,11)
bool_arr=arr1>5
print(bool_arr)
print(arr1[bool_arr])

print(arr[arr>3])

30
[[10 15]
 [25 30]]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[99 99 99 99 99  5  6  7  8  9 10]
