In [4]:
import numpy as np 
my_list=[1,2,3]
arr=np.array(my_list)
print(arr)
arr

[1 2 3]


array([1, 2, 3])

In [7]:
import numpy as np 
my_list=[[1,2,3],[3,4,5],[5,6,7]]
arr=np.array(my_list)
print(arr)
arr
arr1=np.arange(2,12,3)
print(arr1)
arr1

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[ 2  5  8 11]


array([ 2,  5,  8, 11])

In [10]:
import numpy as np 
arr=np.zeros((3,3))
arr1=np.ones(5)
arr2=np.zeros(4)
arr3=np.ones((3,5))
print(arr)
print(arr1)
print(arr2)
print(arr3)
arr4=np.linspace(1,2,30)
print(arr4)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1.         1.03448276 1.06896552 1.10344828 1.13793103 1.17241379
 1.20689655 1.24137931 1.27586207 1.31034483 1.34482759 1.37931034
 1.4137931  1.44827586 1.48275862 1.51724138 1.55172414 1.5862069
 1.62068966 1.65517241 1.68965517 1.72413793 1.75862069 1.79310345
 1.82758621 1.86206897 1.89655172 1.93103448 1.96551724 2.        ]


In [11]:
import  numpy as np 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])