In [4]:
import numpy as np 
my_list=[1,2,3]
arr=np.array(my_list)
print(arr)
arr

[1 2 3]


array([1, 2, 3])

In [7]:
import numpy as np 
my_list=[[1,2,3],[3,4,5],[5,6,7]]
arr=np.array(my_list)
print(arr)
arr
arr1=np.arange(2,12,3)
print(arr1)
arr1

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[ 2  5  8 11]


array([ 2,  5,  8, 11])

In [10]:
import numpy as np 
arr=np.zeros((3,3))
arr1=np.ones(5)
arr2=np.zeros(4)
arr3=np.ones((3,5))
print(arr)
print(arr1)
print(arr2)
print(arr3)
arr4=np.linspace(1,2,30)
print(arr4)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1.         1.03448276 1.06896552 1.10344828 1.13793103 1.17241379
 1.20689655 1.24137931 1.27586207 1.31034483 1.34482759 1.37931034
 1.4137931  1.44827586 1.48275862 1.51724138 1.55172414 1.5862069
 1.62068966 1.65517241 1.68965517 1.72413793 1.75862069 1.79310345
 1.82758621 1.86206897 1.89655172 1.93103448 1.96551724 2.        ]


In [11]:
import  numpy as np 
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
import numpy as np 
arr1=np.random.rand(5)
print(arr1)
arr2=np.random.randn(5)
print(arr2)
arr3=np.random.randint(1,100,25)
print(arr3)
arr=np.arange(25)
print(arr)
ranarr=np.random.randint(0,50,10)
print(ranarr)
larr=arr.reshape(5,5)
print(larr)
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())
print(ranarr.argmin())

[0.82011233 0.24050997 0.83208703 0.20989576 0.63298901]
[ 1.26853722 -0.66826682 -1.06595791 -0.07903955 -0.99971542]
[68 54 30  4 62  7 48 71 70 95 53 33 12 79 95 87 14 25 14 23 71 80 29 25
 60]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[45 21 46  1 15 18 33 14  6 28]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
46
2
1
3


In [2]:
import numpy as np 
arr=np.arange(0,11)
arr[3]
print(arr[3])
print(arr[1:5])
print(arr[2:])

arr[0:5]=99
print(arr)
arr1=np.arange(0,5)
print(arr1[:])
arr_copy=arr1.copy()
arr_copy[:]=False
print(arr_copy)

3
[1 2 3 4]
[ 2  3  4  5  6  7  8  9 10]
[99 99 99 99 99  5  6  7  8  9 10]
[0 1 2 3 4]
[0 0 0 0 0]


In [4]:
import numpy as np 
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d[1,2])
print(arr_2d[:2,1:])
arr1=np.arange(1,11)
bool_arr=arr1>5
print(bool_arr)
print(arr1[bool_arr])

print(arr[arr>3])

30
[[10 15]
 [25 30]]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[99 99 99 99 99  5  6  7  8  9 10]
